# Production Deployment Configuration for RAG Chatbot
version: '3.8'

services:
  # Backend API Service
  chatbot-api:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: rag-chatbot-api:latest
    container_name: rag-chatbot-api
    restart: unless-stopped
    environment:
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - BACKEND_HOST=0.0.0.0
      - BACKEND_PORT=8000
      - DEBUG=False
      - POSTGRES_HOST=chatbot-postgres
      - POSTGRES_PORT=5432
      - POSTGRES_USER=chatbot_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=chatbot_db
      - QDRANT_HOST=qdrant
      - QDRANT_PORT=6333
      - QDRANT_COLLECTION=textbook_content
      - TEXTBOOK_CONTENT_PATH=/app/textbook-content
    ports:
      - "8000:8000"
    volumes:
      - ./website/docs:/app/textbook-content:ro
    depends_on:
      - qdrant
      - chatbot-postgres
    networks:
      - chatbot-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Frontend Docusaurus Service
  chatbot-frontend:
    build:
      context: ./website
      dockerfile: Dockerfile
    image: rag-chatbot-frontend:latest
    container_name: rag-chatbot-frontend
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - CHATBOT_API_URL=http://chatbot-api:8000
    depends_on:
      - chatbot-api
    networks:
      - chatbot-network
    deploy:
      resources:
        limits:
          memory: 512M
          cpus: '0.5'
        reservations:
          memory: 256M
          cpus: '0.25'

  # Vector Database (Qdrant)
  qdrant:
    image: qdrant/qdrant:latest
    container_name: qdrant
    restart: unless-stopped
    ports:
      - "6333:6333"
      - "6334:6334"
    volumes:
      - qdrant_data:/qdrant/storage
    environment:
      - QDRANT_API_KEY=${QDRANT_API_KEY}
    networks:
      - chatbot-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'

  # PostgreSQL Database
  chatbot-postgres:
    image: postgres:15
    container_name: chatbot-postgres
    restart: unless-stopped
    environment:
      - POSTGRES_DB=chatbot_db
      - POSTGRES_USER=chatbot_user
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - chatbot-network
    deploy:
      resources:
        limits:
          memory: 1G
          cpus: '1'
        reservations:
          memory: 512M
          cpus: '0.5'

  # Nginx Reverse Proxy (Optional)
  nginx:
    image: nginx:alpine
    container_name: chatbot-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./ssl:/etc/nginx/ssl
    depends_on:
      - chatbot-frontend
      - chatbot-api
    networks:
      - chatbot-network
    deploy:
      resources:
        limits:
          memory: 128M
          cpus: '0.25'
        reservations:
          memory: 64M
          cpus: '0.1'

networks:
  chatbot-network:
    driver: bridge

volumes:
  qdrant_data:
    driver: local
  postgres_data:
    driver: local